module.exports = {
  apps: [
    {
      name: 'api-dev',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      node_args: '--max-old-space-size=3072',
      max_memory_restart: '3500M',
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'development',
      },
    },
    {
      name: 'TG-bot-dev',
      script: 'dist/bot/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'development',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'userbot-worker-dev',
      script: 'dist/userbot/main.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'development',
        USERBOT_WORKER: 'true',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'giveaway-cron-dev',
      script: 'dist/cron-index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'development',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
  ],
};
