module.exports = {
  apps: [
    {
      name: 'api-primary',
      script: 'dist/index.js',
      instances: '1',
      exec_mode: 'cluster',
      node_args: '--max-old-space-size=3072',
      max_memory_restart: '3500M',
      kill_timeout: 5000,
    },
    {
      name: 'api-replica',
      script: 'dist/index.js',
      instances: '-3',
      exec_mode: 'cluster',
      node_args: '--max-old-space-size=3072',
      max_memory_restart: '3500M',
      kill_timeout: 5000,
    },
    {
      name: 'TG-bot',
      script: 'dist/bot/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'userbot-worker',
      script: 'dist/userbot/main.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        USERBOT_WORKER: 'true',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'giveaway-cron',
      script: 'dist/cron-index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true, // Add timestamps to logs
    },
  ],
};
